p<-rnorm(1000,mean=20,sd=4)
data<-sample(p,100,FALSE)
samplemean<-sum(data)/length(data)
geometricmean<-prod(data)^(0.01)
harmonicmean<-((0.01)*sum(1/data))^-1
rms<-sqrt(0.01*sum(data^2))
print("Samplemean= ")
print(samplemean)
print("Geomean= ")
print(geometricmean)
print("Harmmean= ")
print(harmonicmean)
print("Rms is ")
print(rms)