values=c(1:6)
toss=sample(values,10000,replace=TRUE)
plot.new()
plot(values,prob,ylim = range(0,1))
t1=table(toss)
prop.table(t1)
sink(file = "throwdie.txt",split=2)
cat("------------------------------------------\n")
cat("OUTPUT")
cat("\n----------------------------------------\n")
print(prop.table(t1))
cat("\n----------------------------------------\n")
sink()
