price=read.table("price.txt",header = TRUE)
mean_value=apply(price,2,mean)
mean_value=c("Mean",mean_value[-1])
standard_deviation=apply(price, 2, sd)
standard_deviation=c("SD",standard_deviation[-1])
median_value=apply(price, 2,median)
median_value=c("Median",median_value[-1])
result=rbind(price,mean_value)
result=rbind(result,median_value)
result=rbind(result,standard_deviation)
sink(file = "outputprice.txt")
cat("--------------------------\n")
cat("The resulting table\n")
print(result)
cat("--------------------------\n")
plot(price$No,price$item2,type="l")
lines(price$No,price$item1,col="red")
lines(price$No,price$item3,col="green")
sink()

